// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockvaultClient is a mock of vaultClient interface.
type MockvaultClient struct {
	ctrl     *gomock.Controller
	recorder *MockvaultClientMockRecorder
}

// MockvaultClientMockRecorder is the mock recorder for MockvaultClient.
type MockvaultClientMockRecorder struct {
	mock *MockvaultClient
}

// NewMockvaultClient creates a new mock instance.
func NewMockvaultClient(ctrl *gomock.Controller) *MockvaultClient {
	mock := &MockvaultClient{ctrl: ctrl}
	mock.recorder = &MockvaultClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvaultClient) EXPECT() *MockvaultClientMockRecorder {
	return m.recorder
}
