// Code generated by MockGen. DO NOT EDIT.
// Source: enforcer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockadapter is a mock of adapter interface.
type Mockadapter struct {
	ctrl     *gomock.Controller
	recorder *MockadapterMockRecorder
}

// MockadapterMockRecorder is the mock recorder for Mockadapter.
type MockadapterMockRecorder struct {
	mock *Mockadapter
}

// NewMockadapter creates a new mock instance.
func NewMockadapter(ctrl *gomock.Controller) *Mockadapter {
	mock := &Mockadapter{ctrl: ctrl}
	mock.recorder = &MockadapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockadapter) EXPECT() *MockadapterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockadapter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockadapterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockadapter)(nil).Close))
}

// Mockenforcer is a mock of enforcer interface.
type Mockenforcer struct {
	ctrl     *gomock.Controller
	recorder *MockenforcerMockRecorder
}

// MockenforcerMockRecorder is the mock recorder for Mockenforcer.
type MockenforcerMockRecorder struct {
	mock *Mockenforcer
}

// NewMockenforcer creates a new mock instance.
func NewMockenforcer(ctrl *gomock.Controller) *Mockenforcer {
	mock := &Mockenforcer{ctrl: ctrl}
	mock.recorder = &MockenforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockenforcer) EXPECT() *MockenforcerMockRecorder {
	return m.recorder
}

// LoadPolicy mocks base method.
func (m *Mockenforcer) LoadPolicy() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPolicy")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadPolicy indicates an expected call of LoadPolicy.
func (mr *MockenforcerMockRecorder) LoadPolicy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPolicy", reflect.TypeOf((*Mockenforcer)(nil).LoadPolicy))
}
