// Code generated by "stringer -type=ErrorLevel -trimprefix=Err -output=error_level_string.go"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrLevelDebug-1]
	_ = x[ErrLevelInfo-2]
	_ = x[ErrLevelWarn-3]
	_ = x[ErrLevelError-4]
	_ = x[ErrLevelFatal-5]
	_ = x[ErrLevelPanic-6]
}

const _ErrorLevel_name = "LevelDebugLevelInfoLevelWarnLevelErrorLevelFatalLevelPanic"

var _ErrorLevel_index = [...]uint8{0, 10, 19, 28, 38, 48, 58}

func (i ErrorLevel) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ErrorLevel_index)-1 {
		return "ErrorLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorLevel_name[_ErrorLevel_index[idx]:_ErrorLevel_index[idx+1]]
}
