// Code generated by "stringer -type=fieldID -trimprefix=field -output=field_id_string.go"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldCurrentTime-1]
	_ = x[fieldServiceName-2]
	_ = x[fieldLevel-3]
	_ = x[fieldMessage-4]
	_ = x[fieldErrorCode-5]
	_ = x[fieldTraceID-6]
	_ = x[fieldRequestID-7]
	_ = x[fieldUserID-8]
	_ = x[fieldStackTrace-9]
	_ = x[fieldContext-10]
	_ = x[fieldVersion-11]
	_ = x[fieldKind-12]
	_ = x[fieldCause-13]
	_ = x[fieldIPAddress-14]
	_ = x[fieldOperation-15]
	_ = x[fieldStatus-16]
}

const _fieldID_name = "CurrentTimeServiceNameLevelMessageErrorCodeTraceIDRequestIDUserIDStackTraceContextVersionKindCauseIPAddressOperationStatus"

var _fieldID_index = [...]uint8{0, 11, 22, 27, 34, 43, 50, 59, 65, 75, 82, 89, 93, 98, 107, 116, 122}

func (i fieldID) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_fieldID_index)-1 {
		return "fieldID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _fieldID_name[_fieldID_index[idx]:_fieldID_index[idx+1]]
}
