// Code generated by "stringer -type=Kind -trimprefix=Kind -output=kind_string.go"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindValidation-1]
	_ = x[KindDomain-2]
	_ = x[KindInfra-3]
	_ = x[KindExternal-4]
	_ = x[KindInternal-5]
}

const _Kind_name = "ValidationDomainInfraExternalInternal"

var _Kind_index = [...]uint8{0, 10, 16, 21, 29, 37}

func (i Kind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
