// Code generated by "stringer -type=Status -trimprefix=Status -output=status_string.go"; DO NOT EDIT.

package audit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusStarted-1]
	_ = x[StatusCompleted-2]
	_ = x[StatusCanceled-3]
	_ = x[StatusFailed-4]
}

const _Status_name = "StartedCompletedCanceledFailed"

var _Status_index = [...]uint8{0, 7, 16, 24, 30}

func (i Status) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
