// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockspacesRepo is a mock of spacesRepo interface.
type MockspacesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockspacesRepoMockRecorder
}

// MockspacesRepoMockRecorder is the mock recorder for MockspacesRepo.
type MockspacesRepoMockRecorder struct {
	mock *MockspacesRepo
}

// NewMockspacesRepo creates a new mock instance.
func NewMockspacesRepo(ctrl *gomock.Controller) *MockspacesRepo {
	mock := &MockspacesRepo{ctrl: ctrl}
	mock.recorder = &MockspacesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspacesRepo) EXPECT() *MockspacesRepoMockRecorder {
	return m.recorder
}

// GetSpaceMember mocks base method.
func (m *MockspacesRepo) GetSpaceMember(ctx context.Context, userID, spaceID int) (model.SpaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpaceMember", ctx, userID, spaceID)
	ret0, _ := ret[0].(model.SpaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpaceMember indicates an expected call of GetSpaceMember.
func (mr *MockspacesRepoMockRecorder) GetSpaceMember(ctx, userID, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpaceMember", reflect.TypeOf((*MockspacesRepo)(nil).GetSpaceMember), ctx, userID, spaceID)
}
