// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openfga/go-sdk/client (interfaces: SdkClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	openfga "github.com/openfga/go-sdk"
	client "github.com/openfga/go-sdk/client"
)

// MockSdkClient is a mock of SdkClient interface.
type MockSdkClient struct {
	ctrl     *gomock.Controller
	recorder *MockSdkClientMockRecorder
}

// MockSdkClientMockRecorder is the mock recorder for MockSdkClient.
type MockSdkClientMockRecorder struct {
	mock *MockSdkClient
}

// NewMockSdkClient creates a new mock instance.
func NewMockSdkClient(ctrl *gomock.Controller) *MockSdkClient {
	mock := &MockSdkClient{ctrl: ctrl}
	mock.recorder = &MockSdkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSdkClient) EXPECT() *MockSdkClientMockRecorder {
	return m.recorder
}

// BatchCheck mocks base method.
func (m *MockSdkClient) BatchCheck(arg0 context.Context) client.SdkClientBatchCheckRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCheck", arg0)
	ret0, _ := ret[0].(client.SdkClientBatchCheckRequestInterface)
	return ret0
}

// BatchCheck indicates an expected call of BatchCheck.
func (mr *MockSdkClientMockRecorder) BatchCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCheck", reflect.TypeOf((*MockSdkClient)(nil).BatchCheck), arg0)
}

// BatchCheckExecute mocks base method.
func (m *MockSdkClient) BatchCheckExecute(arg0 client.SdkClientBatchCheckRequestInterface) (*openfga.BatchCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCheckExecute", arg0)
	ret0, _ := ret[0].(*openfga.BatchCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCheckExecute indicates an expected call of BatchCheckExecute.
func (mr *MockSdkClientMockRecorder) BatchCheckExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCheckExecute", reflect.TypeOf((*MockSdkClient)(nil).BatchCheckExecute), arg0)
}

// Check mocks base method.
func (m *MockSdkClient) Check(arg0 context.Context) client.SdkClientCheckRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(client.SdkClientCheckRequestInterface)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockSdkClientMockRecorder) Check(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSdkClient)(nil).Check), arg0)
}

// CheckExecute mocks base method.
func (m *MockSdkClient) CheckExecute(arg0 client.SdkClientCheckRequestInterface) (*client.ClientCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExecute", arg0)
	ret0, _ := ret[0].(*client.ClientCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExecute indicates an expected call of CheckExecute.
func (mr *MockSdkClientMockRecorder) CheckExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExecute", reflect.TypeOf((*MockSdkClient)(nil).CheckExecute), arg0)
}

// ClientBatchCheck mocks base method.
func (m *MockSdkClient) ClientBatchCheck(arg0 context.Context) client.SdkClientBatchCheckClientRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientBatchCheck", arg0)
	ret0, _ := ret[0].(client.SdkClientBatchCheckClientRequestInterface)
	return ret0
}

// ClientBatchCheck indicates an expected call of ClientBatchCheck.
func (mr *MockSdkClientMockRecorder) ClientBatchCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientBatchCheck", reflect.TypeOf((*MockSdkClient)(nil).ClientBatchCheck), arg0)
}

// ClientBatchCheckExecute mocks base method.
func (m *MockSdkClient) ClientBatchCheckExecute(arg0 client.SdkClientBatchCheckClientRequestInterface) (*[]client.ClientBatchCheckClientSingleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientBatchCheckExecute", arg0)
	ret0, _ := ret[0].(*[]client.ClientBatchCheckClientSingleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientBatchCheckExecute indicates an expected call of ClientBatchCheckExecute.
func (mr *MockSdkClientMockRecorder) ClientBatchCheckExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientBatchCheckExecute", reflect.TypeOf((*MockSdkClient)(nil).ClientBatchCheckExecute), arg0)
}

// CreateStore mocks base method.
func (m *MockSdkClient) CreateStore(arg0 context.Context) client.SdkClientCreateStoreRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", arg0)
	ret0, _ := ret[0].(client.SdkClientCreateStoreRequestInterface)
	return ret0
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockSdkClientMockRecorder) CreateStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockSdkClient)(nil).CreateStore), arg0)
}

// CreateStoreExecute mocks base method.
func (m *MockSdkClient) CreateStoreExecute(arg0 client.SdkClientCreateStoreRequestInterface) (*openfga.CreateStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoreExecute", arg0)
	ret0, _ := ret[0].(*openfga.CreateStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoreExecute indicates an expected call of CreateStoreExecute.
func (mr *MockSdkClientMockRecorder) CreateStoreExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoreExecute", reflect.TypeOf((*MockSdkClient)(nil).CreateStoreExecute), arg0)
}

// DeleteStore mocks base method.
func (m *MockSdkClient) DeleteStore(arg0 context.Context) client.SdkClientDeleteStoreRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStore", arg0)
	ret0, _ := ret[0].(client.SdkClientDeleteStoreRequestInterface)
	return ret0
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockSdkClientMockRecorder) DeleteStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockSdkClient)(nil).DeleteStore), arg0)
}

// DeleteStoreExecute mocks base method.
func (m *MockSdkClient) DeleteStoreExecute(arg0 client.SdkClientDeleteStoreRequestInterface) (*client.ClientDeleteStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoreExecute", arg0)
	ret0, _ := ret[0].(*client.ClientDeleteStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStoreExecute indicates an expected call of DeleteStoreExecute.
func (mr *MockSdkClientMockRecorder) DeleteStoreExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoreExecute", reflect.TypeOf((*MockSdkClient)(nil).DeleteStoreExecute), arg0)
}

// DeleteTuples mocks base method.
func (m *MockSdkClient) DeleteTuples(arg0 context.Context) client.SdkClientDeleteTuplesRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTuples", arg0)
	ret0, _ := ret[0].(client.SdkClientDeleteTuplesRequestInterface)
	return ret0
}

// DeleteTuples indicates an expected call of DeleteTuples.
func (mr *MockSdkClientMockRecorder) DeleteTuples(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTuples", reflect.TypeOf((*MockSdkClient)(nil).DeleteTuples), arg0)
}

// DeleteTuplesExecute mocks base method.
func (m *MockSdkClient) DeleteTuplesExecute(arg0 client.SdkClientDeleteTuplesRequestInterface) (*client.ClientWriteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTuplesExecute", arg0)
	ret0, _ := ret[0].(*client.ClientWriteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTuplesExecute indicates an expected call of DeleteTuplesExecute.
func (mr *MockSdkClientMockRecorder) DeleteTuplesExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTuplesExecute", reflect.TypeOf((*MockSdkClient)(nil).DeleteTuplesExecute), arg0)
}

// Expand mocks base method.
func (m *MockSdkClient) Expand(arg0 context.Context) client.SdkClientExpandRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expand", arg0)
	ret0, _ := ret[0].(client.SdkClientExpandRequestInterface)
	return ret0
}

// Expand indicates an expected call of Expand.
func (mr *MockSdkClientMockRecorder) Expand(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expand", reflect.TypeOf((*MockSdkClient)(nil).Expand), arg0)
}

// ExpandExecute mocks base method.
func (m *MockSdkClient) ExpandExecute(arg0 client.SdkClientExpandRequestInterface) (*openfga.ExpandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandExecute", arg0)
	ret0, _ := ret[0].(*openfga.ExpandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpandExecute indicates an expected call of ExpandExecute.
func (mr *MockSdkClientMockRecorder) ExpandExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandExecute", reflect.TypeOf((*MockSdkClient)(nil).ExpandExecute), arg0)
}

// GetAuthorizationModelId mocks base method.
func (m *MockSdkClient) GetAuthorizationModelId() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationModelId")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationModelId indicates an expected call of GetAuthorizationModelId.
func (mr *MockSdkClientMockRecorder) GetAuthorizationModelId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationModelId", reflect.TypeOf((*MockSdkClient)(nil).GetAuthorizationModelId))
}

// GetStore mocks base method.
func (m *MockSdkClient) GetStore(arg0 context.Context) client.SdkClientGetStoreRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", arg0)
	ret0, _ := ret[0].(client.SdkClientGetStoreRequestInterface)
	return ret0
}

// GetStore indicates an expected call of GetStore.
func (mr *MockSdkClientMockRecorder) GetStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockSdkClient)(nil).GetStore), arg0)
}

// GetStoreExecute mocks base method.
func (m *MockSdkClient) GetStoreExecute(arg0 client.SdkClientGetStoreRequestInterface) (*openfga.GetStoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreExecute", arg0)
	ret0, _ := ret[0].(*openfga.GetStoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreExecute indicates an expected call of GetStoreExecute.
func (mr *MockSdkClientMockRecorder) GetStoreExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreExecute", reflect.TypeOf((*MockSdkClient)(nil).GetStoreExecute), arg0)
}

// GetStoreId mocks base method.
func (m *MockSdkClient) GetStoreId() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreId")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreId indicates an expected call of GetStoreId.
func (mr *MockSdkClientMockRecorder) GetStoreId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreId", reflect.TypeOf((*MockSdkClient)(nil).GetStoreId))
}

// ListObjects mocks base method.
func (m *MockSdkClient) ListObjects(arg0 context.Context) client.SdkClientListObjectsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", arg0)
	ret0, _ := ret[0].(client.SdkClientListObjectsRequestInterface)
	return ret0
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockSdkClientMockRecorder) ListObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockSdkClient)(nil).ListObjects), arg0)
}

// ListObjectsExecute mocks base method.
func (m *MockSdkClient) ListObjectsExecute(arg0 client.SdkClientListObjectsRequestInterface) (*openfga.ListObjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectsExecute", arg0)
	ret0, _ := ret[0].(*openfga.ListObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectsExecute indicates an expected call of ListObjectsExecute.
func (mr *MockSdkClientMockRecorder) ListObjectsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsExecute", reflect.TypeOf((*MockSdkClient)(nil).ListObjectsExecute), arg0)
}

// ListRelations mocks base method.
func (m *MockSdkClient) ListRelations(arg0 context.Context) client.SdkClientListRelationsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelations", arg0)
	ret0, _ := ret[0].(client.SdkClientListRelationsRequestInterface)
	return ret0
}

// ListRelations indicates an expected call of ListRelations.
func (mr *MockSdkClientMockRecorder) ListRelations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelations", reflect.TypeOf((*MockSdkClient)(nil).ListRelations), arg0)
}

// ListRelationsExecute mocks base method.
func (m *MockSdkClient) ListRelationsExecute(arg0 client.SdkClientListRelationsRequestInterface) (*client.ClientListRelationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelationsExecute", arg0)
	ret0, _ := ret[0].(*client.ClientListRelationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelationsExecute indicates an expected call of ListRelationsExecute.
func (mr *MockSdkClientMockRecorder) ListRelationsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelationsExecute", reflect.TypeOf((*MockSdkClient)(nil).ListRelationsExecute), arg0)
}

// ListStores mocks base method.
func (m *MockSdkClient) ListStores(arg0 context.Context) client.SdkClientListStoresRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStores", arg0)
	ret0, _ := ret[0].(client.SdkClientListStoresRequestInterface)
	return ret0
}

// ListStores indicates an expected call of ListStores.
func (mr *MockSdkClientMockRecorder) ListStores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockSdkClient)(nil).ListStores), arg0)
}

// ListStoresExecute mocks base method.
func (m *MockSdkClient) ListStoresExecute(arg0 client.SdkClientListStoresRequestInterface) (*openfga.ListStoresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoresExecute", arg0)
	ret0, _ := ret[0].(*openfga.ListStoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoresExecute indicates an expected call of ListStoresExecute.
func (mr *MockSdkClientMockRecorder) ListStoresExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoresExecute", reflect.TypeOf((*MockSdkClient)(nil).ListStoresExecute), arg0)
}

// ListUsers mocks base method.
func (m *MockSdkClient) ListUsers(arg0 context.Context) client.SdkClientListUsersRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0)
	ret0, _ := ret[0].(client.SdkClientListUsersRequestInterface)
	return ret0
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockSdkClientMockRecorder) ListUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockSdkClient)(nil).ListUsers), arg0)
}

// ListUsersExecute mocks base method.
func (m *MockSdkClient) ListUsersExecute(arg0 client.SdkClientListUsersRequestInterface) (*openfga.ListUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersExecute", arg0)
	ret0, _ := ret[0].(*openfga.ListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersExecute indicates an expected call of ListUsersExecute.
func (mr *MockSdkClientMockRecorder) ListUsersExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersExecute", reflect.TypeOf((*MockSdkClient)(nil).ListUsersExecute), arg0)
}

// Read mocks base method.
func (m *MockSdkClient) Read(arg0 context.Context) client.SdkClientReadRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(client.SdkClientReadRequestInterface)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockSdkClientMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockSdkClient)(nil).Read), arg0)
}

// ReadAssertions mocks base method.
func (m *MockSdkClient) ReadAssertions(arg0 context.Context) client.SdkClientReadAssertionsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAssertions", arg0)
	ret0, _ := ret[0].(client.SdkClientReadAssertionsRequestInterface)
	return ret0
}

// ReadAssertions indicates an expected call of ReadAssertions.
func (mr *MockSdkClientMockRecorder) ReadAssertions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAssertions", reflect.TypeOf((*MockSdkClient)(nil).ReadAssertions), arg0)
}

// ReadAssertionsExecute mocks base method.
func (m *MockSdkClient) ReadAssertionsExecute(arg0 client.SdkClientReadAssertionsRequestInterface) (*openfga.ReadAssertionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAssertionsExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadAssertionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAssertionsExecute indicates an expected call of ReadAssertionsExecute.
func (mr *MockSdkClientMockRecorder) ReadAssertionsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAssertionsExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadAssertionsExecute), arg0)
}

// ReadAuthorizationModel mocks base method.
func (m *MockSdkClient) ReadAuthorizationModel(arg0 context.Context) client.SdkClientReadAuthorizationModelRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAuthorizationModel", arg0)
	ret0, _ := ret[0].(client.SdkClientReadAuthorizationModelRequestInterface)
	return ret0
}

// ReadAuthorizationModel indicates an expected call of ReadAuthorizationModel.
func (mr *MockSdkClientMockRecorder) ReadAuthorizationModel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAuthorizationModel", reflect.TypeOf((*MockSdkClient)(nil).ReadAuthorizationModel), arg0)
}

// ReadAuthorizationModelExecute mocks base method.
func (m *MockSdkClient) ReadAuthorizationModelExecute(arg0 client.SdkClientReadAuthorizationModelRequestInterface) (*openfga.ReadAuthorizationModelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAuthorizationModelExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadAuthorizationModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAuthorizationModelExecute indicates an expected call of ReadAuthorizationModelExecute.
func (mr *MockSdkClientMockRecorder) ReadAuthorizationModelExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAuthorizationModelExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadAuthorizationModelExecute), arg0)
}

// ReadAuthorizationModels mocks base method.
func (m *MockSdkClient) ReadAuthorizationModels(arg0 context.Context) client.SdkClientReadAuthorizationModelsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAuthorizationModels", arg0)
	ret0, _ := ret[0].(client.SdkClientReadAuthorizationModelsRequestInterface)
	return ret0
}

// ReadAuthorizationModels indicates an expected call of ReadAuthorizationModels.
func (mr *MockSdkClientMockRecorder) ReadAuthorizationModels(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAuthorizationModels", reflect.TypeOf((*MockSdkClient)(nil).ReadAuthorizationModels), arg0)
}

// ReadAuthorizationModelsExecute mocks base method.
func (m *MockSdkClient) ReadAuthorizationModelsExecute(arg0 client.SdkClientReadAuthorizationModelsRequestInterface) (*openfga.ReadAuthorizationModelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAuthorizationModelsExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadAuthorizationModelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAuthorizationModelsExecute indicates an expected call of ReadAuthorizationModelsExecute.
func (mr *MockSdkClientMockRecorder) ReadAuthorizationModelsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAuthorizationModelsExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadAuthorizationModelsExecute), arg0)
}

// ReadChanges mocks base method.
func (m *MockSdkClient) ReadChanges(arg0 context.Context) client.SdkClientReadChangesRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadChanges", arg0)
	ret0, _ := ret[0].(client.SdkClientReadChangesRequestInterface)
	return ret0
}

// ReadChanges indicates an expected call of ReadChanges.
func (mr *MockSdkClientMockRecorder) ReadChanges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadChanges", reflect.TypeOf((*MockSdkClient)(nil).ReadChanges), arg0)
}

// ReadChangesExecute mocks base method.
func (m *MockSdkClient) ReadChangesExecute(arg0 client.SdkClientReadChangesRequestInterface) (*openfga.ReadChangesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadChangesExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadChangesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadChangesExecute indicates an expected call of ReadChangesExecute.
func (mr *MockSdkClientMockRecorder) ReadChangesExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadChangesExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadChangesExecute), arg0)
}

// ReadExecute mocks base method.
func (m *MockSdkClient) ReadExecute(arg0 client.SdkClientReadRequestInterface) (*openfga.ReadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadExecute indicates an expected call of ReadExecute.
func (mr *MockSdkClientMockRecorder) ReadExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadExecute), arg0)
}

// ReadLatestAuthorizationModel mocks base method.
func (m *MockSdkClient) ReadLatestAuthorizationModel(arg0 context.Context) client.SdkClientReadLatestAuthorizationModelRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLatestAuthorizationModel", arg0)
	ret0, _ := ret[0].(client.SdkClientReadLatestAuthorizationModelRequestInterface)
	return ret0
}

// ReadLatestAuthorizationModel indicates an expected call of ReadLatestAuthorizationModel.
func (mr *MockSdkClientMockRecorder) ReadLatestAuthorizationModel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLatestAuthorizationModel", reflect.TypeOf((*MockSdkClient)(nil).ReadLatestAuthorizationModel), arg0)
}

// ReadLatestAuthorizationModelExecute mocks base method.
func (m *MockSdkClient) ReadLatestAuthorizationModelExecute(arg0 client.SdkClientReadLatestAuthorizationModelRequestInterface) (*openfga.ReadAuthorizationModelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLatestAuthorizationModelExecute", arg0)
	ret0, _ := ret[0].(*openfga.ReadAuthorizationModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLatestAuthorizationModelExecute indicates an expected call of ReadLatestAuthorizationModelExecute.
func (mr *MockSdkClientMockRecorder) ReadLatestAuthorizationModelExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLatestAuthorizationModelExecute", reflect.TypeOf((*MockSdkClient)(nil).ReadLatestAuthorizationModelExecute), arg0)
}

// SetAuthorizationModelId mocks base method.
func (m *MockSdkClient) SetAuthorizationModelId(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAuthorizationModelId", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAuthorizationModelId indicates an expected call of SetAuthorizationModelId.
func (mr *MockSdkClientMockRecorder) SetAuthorizationModelId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthorizationModelId", reflect.TypeOf((*MockSdkClient)(nil).SetAuthorizationModelId), arg0)
}

// SetStoreId mocks base method.
func (m *MockSdkClient) SetStoreId(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoreId", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStoreId indicates an expected call of SetStoreId.
func (mr *MockSdkClientMockRecorder) SetStoreId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoreId", reflect.TypeOf((*MockSdkClient)(nil).SetStoreId), arg0)
}

// StreamedListObjects mocks base method.
func (m *MockSdkClient) StreamedListObjects(arg0 context.Context) client.SdkClientStreamedListObjectsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamedListObjects", arg0)
	ret0, _ := ret[0].(client.SdkClientStreamedListObjectsRequestInterface)
	return ret0
}

// StreamedListObjects indicates an expected call of StreamedListObjects.
func (mr *MockSdkClientMockRecorder) StreamedListObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamedListObjects", reflect.TypeOf((*MockSdkClient)(nil).StreamedListObjects), arg0)
}

// StreamedListObjectsExecute mocks base method.
func (m *MockSdkClient) StreamedListObjectsExecute(arg0 client.SdkClientStreamedListObjectsRequestInterface) (*client.ClientStreamedListObjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamedListObjectsExecute", arg0)
	ret0, _ := ret[0].(*client.ClientStreamedListObjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamedListObjectsExecute indicates an expected call of StreamedListObjectsExecute.
func (mr *MockSdkClientMockRecorder) StreamedListObjectsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamedListObjectsExecute", reflect.TypeOf((*MockSdkClient)(nil).StreamedListObjectsExecute), arg0)
}

// Write mocks base method.
func (m *MockSdkClient) Write(arg0 context.Context) client.SdkClientWriteRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(client.SdkClientWriteRequestInterface)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockSdkClientMockRecorder) Write(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSdkClient)(nil).Write), arg0)
}

// WriteAssertions mocks base method.
func (m *MockSdkClient) WriteAssertions(arg0 context.Context) client.SdkClientWriteAssertionsRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAssertions", arg0)
	ret0, _ := ret[0].(client.SdkClientWriteAssertionsRequestInterface)
	return ret0
}

// WriteAssertions indicates an expected call of WriteAssertions.
func (mr *MockSdkClientMockRecorder) WriteAssertions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAssertions", reflect.TypeOf((*MockSdkClient)(nil).WriteAssertions), arg0)
}

// WriteAssertionsExecute mocks base method.
func (m *MockSdkClient) WriteAssertionsExecute(arg0 client.SdkClientWriteAssertionsRequestInterface) (*client.ClientWriteAssertionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAssertionsExecute", arg0)
	ret0, _ := ret[0].(*client.ClientWriteAssertionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAssertionsExecute indicates an expected call of WriteAssertionsExecute.
func (mr *MockSdkClientMockRecorder) WriteAssertionsExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAssertionsExecute", reflect.TypeOf((*MockSdkClient)(nil).WriteAssertionsExecute), arg0)
}

// WriteAuthorizationModel mocks base method.
func (m *MockSdkClient) WriteAuthorizationModel(arg0 context.Context) client.SdkClientWriteAuthorizationModelRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAuthorizationModel", arg0)
	ret0, _ := ret[0].(client.SdkClientWriteAuthorizationModelRequestInterface)
	return ret0
}

// WriteAuthorizationModel indicates an expected call of WriteAuthorizationModel.
func (mr *MockSdkClientMockRecorder) WriteAuthorizationModel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAuthorizationModel", reflect.TypeOf((*MockSdkClient)(nil).WriteAuthorizationModel), arg0)
}

// WriteAuthorizationModelExecute mocks base method.
func (m *MockSdkClient) WriteAuthorizationModelExecute(arg0 client.SdkClientWriteAuthorizationModelRequestInterface) (*openfga.WriteAuthorizationModelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAuthorizationModelExecute", arg0)
	ret0, _ := ret[0].(*openfga.WriteAuthorizationModelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAuthorizationModelExecute indicates an expected call of WriteAuthorizationModelExecute.
func (mr *MockSdkClientMockRecorder) WriteAuthorizationModelExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAuthorizationModelExecute", reflect.TypeOf((*MockSdkClient)(nil).WriteAuthorizationModelExecute), arg0)
}

// WriteExecute mocks base method.
func (m *MockSdkClient) WriteExecute(arg0 client.SdkClientWriteRequestInterface) (*client.ClientWriteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteExecute", arg0)
	ret0, _ := ret[0].(*client.ClientWriteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteExecute indicates an expected call of WriteExecute.
func (mr *MockSdkClientMockRecorder) WriteExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteExecute", reflect.TypeOf((*MockSdkClient)(nil).WriteExecute), arg0)
}

// WriteTuples mocks base method.
func (m *MockSdkClient) WriteTuples(arg0 context.Context) client.SdkClientWriteTuplesRequestInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTuples", arg0)
	ret0, _ := ret[0].(client.SdkClientWriteTuplesRequestInterface)
	return ret0
}

// WriteTuples indicates an expected call of WriteTuples.
func (mr *MockSdkClientMockRecorder) WriteTuples(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTuples", reflect.TypeOf((*MockSdkClient)(nil).WriteTuples), arg0)
}

// WriteTuplesExecute mocks base method.
func (m *MockSdkClient) WriteTuplesExecute(arg0 client.SdkClientWriteTuplesRequestInterface) (*client.ClientWriteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTuplesExecute", arg0)
	ret0, _ := ret[0].(*client.ClientWriteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteTuplesExecute indicates an expected call of WriteTuplesExecute.
func (mr *MockSdkClientMockRecorder) WriteTuplesExecute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTuplesExecute", reflect.TypeOf((*MockSdkClient)(nil).WriteTuplesExecute), arg0)
}
