// Code generated by MockGen. DO NOT EDIT.
// Source: fga.go

// Package mocks is a generated GoMock package.
package mocks

import (
	audit "auth-service/pkg/audit"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// Mockauditor is a mock of auditor interface.
type Mockauditor struct {
	ctrl     *gomock.Controller
	recorder *MockauditorMockRecorder
}

// MockauditorMockRecorder is the mock recorder for Mockauditor.
type MockauditorMockRecorder struct {
	mock *Mockauditor
}

// NewMockauditor creates a new mock instance.
func NewMockauditor(ctrl *gomock.Controller) *Mockauditor {
	mock := &Mockauditor{ctrl: ctrl}
	mock.recorder = &MockauditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockauditor) EXPECT() *MockauditorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Mockauditor) Create(ctx context.Context) audit.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(audit.Event)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockauditorMockRecorder) Create(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Mockauditor)(nil).Create), ctx)
}

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// GetUserIDByTelegramID mocks base method.
func (m *MockuserRepo) GetUserIDByTelegramID(ctx context.Context, telegramID string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByTelegramID indicates an expected call of GetUserIDByTelegramID.
func (mr *MockuserRepoMockRecorder) GetUserIDByTelegramID(ctx, telegramID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByTelegramID", reflect.TypeOf((*MockuserRepo)(nil).GetUserIDByTelegramID), ctx, telegramID)
}
