// Code generated by MockGen. DO NOT EDIT.
// Source: note.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// GetNotesVisibility mocks base method.
func (m *Mockstorage) GetNotesVisibility(ctx context.Context, ids []uuid.UUID) ([]model.NoteVisibility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotesVisibility", ctx, ids)
	ret0, _ := ret[0].([]model.NoteVisibility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotesVisibility indicates an expected call of GetNotesVisibility.
func (mr *MockstorageMockRecorder) GetNotesVisibility(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotesVisibility", reflect.TypeOf((*Mockstorage)(nil).GetNotesVisibility), ctx, ids)
}
