// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// FilterNoteIDs mocks base method.
func (m *Mockstorage) FilterNoteIDs(ctx context.Context, spaceID int, ids []int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNoteIDs", ctx, spaceID, ids)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterNoteIDs indicates an expected call of FilterNoteIDs.
func (mr *MockstorageMockRecorder) FilterNoteIDs(ctx, spaceID, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNoteIDs", reflect.TypeOf((*Mockstorage)(nil).FilterNoteIDs), ctx, spaceID, ids)
}

// MockspaceAccessChecker is a mock of spaceAccessChecker interface.
type MockspaceAccessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockspaceAccessCheckerMockRecorder
}

// MockspaceAccessCheckerMockRecorder is the mock recorder for MockspaceAccessChecker.
type MockspaceAccessCheckerMockRecorder struct {
	mock *MockspaceAccessChecker
}

// NewMockspaceAccessChecker creates a new mock instance.
func NewMockspaceAccessChecker(ctrl *gomock.Controller) *MockspaceAccessChecker {
	mock := &MockspaceAccessChecker{ctrl: ctrl}
	mock.recorder = &MockspaceAccessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockspaceAccessChecker) EXPECT() *MockspaceAccessCheckerMockRecorder {
	return m.recorder
}

// CheckSpaceAccess mocks base method.
func (m *MockspaceAccessChecker) CheckSpaceAccess(ctx context.Context, userID, spaceID int) (model.SpaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSpaceAccess", ctx, userID, spaceID)
	ret0, _ := ret[0].(model.SpaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSpaceAccess indicates an expected call of CheckSpaceAccess.
func (mr *MockspaceAccessCheckerMockRecorder) CheckSpaceAccess(ctx, userID, spaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSpaceAccess", reflect.TypeOf((*MockspaceAccessChecker)(nil).CheckSpaceAccess), ctx, userID, spaceID)
}

// MocknotePermissionResolver is a mock of notePermissionResolver interface.
type MocknotePermissionResolver struct {
	ctrl     *gomock.Controller
	recorder *MocknotePermissionResolverMockRecorder
}

// MocknotePermissionResolverMockRecorder is the mock recorder for MocknotePermissionResolver.
type MocknotePermissionResolverMockRecorder struct {
	mock *MocknotePermissionResolver
}

// NewMocknotePermissionResolver creates a new mock instance.
func NewMocknotePermissionResolver(ctrl *gomock.Controller) *MocknotePermissionResolver {
	mock := &MocknotePermissionResolver{ctrl: ctrl}
	mock.recorder = &MocknotePermissionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotePermissionResolver) EXPECT() *MocknotePermissionResolverMockRecorder {
	return m.recorder
}

// ResolveNotePermissions mocks base method.
func (m *MocknotePermissionResolver) ResolveNotePermissions(ctx context.Context, access model.SpaceMember, noteIDs []int) (map[int]model.NoteAccessInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveNotePermissions", ctx, access, noteIDs)
	ret0, _ := ret[0].(map[int]model.NoteAccessInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveNotePermissions indicates an expected call of ResolveNotePermissions.
func (mr *MocknotePermissionResolverMockRecorder) ResolveNotePermissions(ctx, access, noteIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveNotePermissions", reflect.TypeOf((*MocknotePermissionResolver)(nil).ResolveNotePermissions), ctx, access, noteIDs)
}
