// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockredisClient is a mock of redisClient interface.
type MockredisClient struct {
	ctrl     *gomock.Controller
	recorder *MockredisClientMockRecorder
}

// MockredisClientMockRecorder is the mock recorder for MockredisClient.
type MockredisClientMockRecorder struct {
	mock *MockredisClient
}

// NewMockredisClient creates a new mock instance.
func NewMockredisClient(ctrl *gomock.Controller) *MockredisClient {
	mock := &MockredisClient{ctrl: ctrl}
	mock.recorder = &MockredisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockredisClient) EXPECT() *MockredisClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockredisClient) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockredisClientMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockredisClient)(nil).Close), ctx)
}

// Connect mocks base method.
func (m *MockredisClient) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockredisClientMockRecorder) Connect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockredisClient)(nil).Connect), ctx)
}
