// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockauthSerivce is a mock of authSerivce interface.
type MockauthSerivce struct {
	ctrl     *gomock.Controller
	recorder *MockauthSerivceMockRecorder
}

// MockauthSerivceMockRecorder is the mock recorder for MockauthSerivce.
type MockauthSerivceMockRecorder struct {
	mock *MockauthSerivce
}

// NewMockauthSerivce creates a new mock instance.
func NewMockauthSerivce(ctrl *gomock.Controller) *MockauthSerivce {
	mock := &MockauthSerivce{ctrl: ctrl}
	mock.recorder = &MockauthSerivceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthSerivce) EXPECT() *MockauthSerivceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockauthSerivce) Login(arg0 context.Context, arg1 model.LoginRequest) (model.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(model.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthSerivceMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthSerivce)(nil).Login), arg0, arg1)
}
