// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockauthProcessorHandler is a mock of authProcessorHandler interface.
type MockauthProcessorHandler struct {
	ctrl     *gomock.Controller
	recorder *MockauthProcessorHandlerMockRecorder
}

// MockauthProcessorHandlerMockRecorder is the mock recorder for MockauthProcessorHandler.
type MockauthProcessorHandlerMockRecorder struct {
	mock *MockauthProcessorHandler
}

// NewMockauthProcessorHandler creates a new mock instance.
func NewMockauthProcessorHandler(ctrl *gomock.Controller) *MockauthProcessorHandler {
	mock := &MockauthProcessorHandler{ctrl: ctrl}
	mock.recorder = &MockauthProcessorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthProcessorHandler) EXPECT() *MockauthProcessorHandlerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockauthProcessorHandler) Login(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockauthProcessorHandlerMockRecorder) Login(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthProcessorHandler)(nil).Login), c)
}

// MocknotesProcessorHandler is a mock of notesProcessorHandler interface.
type MocknotesProcessorHandler struct {
	ctrl     *gomock.Controller
	recorder *MocknotesProcessorHandlerMockRecorder
}

// MocknotesProcessorHandlerMockRecorder is the mock recorder for MocknotesProcessorHandler.
type MocknotesProcessorHandlerMockRecorder struct {
	mock *MocknotesProcessorHandler
}

// NewMocknotesProcessorHandler creates a new mock instance.
func NewMocknotesProcessorHandler(ctrl *gomock.Controller) *MocknotesProcessorHandler {
	mock := &MocknotesProcessorHandler{ctrl: ctrl}
	mock.recorder = &MocknotesProcessorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotesProcessorHandler) EXPECT() *MocknotesProcessorHandlerMockRecorder {
	return m.recorder
}

// FilterNotes mocks base method.
func (m *MocknotesProcessorHandler) FilterNotes(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNotes", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterNotes indicates an expected call of FilterNotes.
func (mr *MocknotesProcessorHandlerMockRecorder) FilterNotes(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNotes", reflect.TypeOf((*MocknotesProcessorHandler)(nil).FilterNotes), c)
}
