// Code generated by MockGen. DO NOT EDIT.
// Source: middleware.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockAuthService) CheckToken(authHeader string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", authHeader)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockAuthServiceMockRecorder) CheckToken(authHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockAuthService)(nil).CheckToken), authHeader)
}

// GetIssuer mocks base method.
func (m *MockAuthService) GetIssuer() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuer")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIssuer indicates an expected call of GetIssuer.
func (mr *MockAuthServiceMockRecorder) GetIssuer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuer", reflect.TypeOf((*MockAuthService)(nil).GetIssuer))
}

// GetPayload mocks base method.
func (m *MockAuthService) GetPayload(token *jwt.Token) (jwt.MapClaims, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload", token)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockAuthServiceMockRecorder) GetPayload(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockAuthService)(nil).GetPayload), token)
}

// GetServiceClient mocks base method.
func (m *MockAuthService) GetServiceClient(ctx context.Context, clientID string) (model.ServiceClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceClient", ctx, clientID)
	ret0, _ := ret[0].(model.ServiceClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceClient indicates an expected call of GetServiceClient.
func (mr *MockAuthServiceMockRecorder) GetServiceClient(ctx, clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceClient", reflect.TypeOf((*MockAuthService)(nil).GetServiceClient), ctx, clientID)
}
