// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockAuthService) CheckToken(authHeader string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", authHeader)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockAuthServiceMockRecorder) CheckToken(authHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockAuthService)(nil).CheckToken), authHeader)
}

// GetPayload mocks base method.
func (m *MockAuthService) GetPayload(token *jwt.Token) (jwt.MapClaims, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayload", token)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPayload indicates an expected call of GetPayload.
func (mr *MockAuthServiceMockRecorder) GetPayload(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayload", reflect.TypeOf((*MockAuthService)(nil).GetPayload), token)
}

// MockPoliticsService is a mock of PoliticsService interface.
type MockPoliticsService struct {
	ctrl     *gomock.Controller
	recorder *MockPoliticsServiceMockRecorder
}

// MockPoliticsServiceMockRecorder is the mock recorder for MockPoliticsService.
type MockPoliticsServiceMockRecorder struct {
	mock *MockPoliticsService
}

// NewMockPoliticsService creates a new mock instance.
func NewMockPoliticsService(ctrl *gomock.Controller) *MockPoliticsService {
	mock := &MockPoliticsService{ctrl: ctrl}
	mock.recorder = &MockPoliticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoliticsService) EXPECT() *MockPoliticsServiceMockRecorder {
	return m.recorder
}

// FilterNotes mocks base method.
func (m *MockPoliticsService) FilterNotes(ctx context.Context, req model.FilterNotesRequest) (map[int]model.NoteAccessInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNotes", ctx, req)
	ret0, _ := ret[0].(map[int]model.NoteAccessInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterNotes indicates an expected call of FilterNotes.
func (mr *MockPoliticsServiceMockRecorder) FilterNotes(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNotes", reflect.TypeOf((*MockPoliticsService)(nil).FilterNotes), ctx, req)
}
