// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPoliticsService is a mock of PoliticsService interface.
type MockPoliticsService struct {
	ctrl     *gomock.Controller
	recorder *MockPoliticsServiceMockRecorder
}

// MockPoliticsServiceMockRecorder is the mock recorder for MockPoliticsService.
type MockPoliticsServiceMockRecorder struct {
	mock *MockPoliticsService
}

// NewMockPoliticsService creates a new mock instance.
func NewMockPoliticsService(ctrl *gomock.Controller) *MockPoliticsService {
	mock := &MockPoliticsService{ctrl: ctrl}
	mock.recorder = &MockPoliticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoliticsService) EXPECT() *MockPoliticsServiceMockRecorder {
	return m.recorder
}

// FilterNotes mocks base method.
func (m *MockPoliticsService) FilterNotes(ctx context.Context, req model.FilterNotesRequest) (map[uuid.UUID]model.NoteAccessInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNotes", ctx, req)
	ret0, _ := ret[0].(map[uuid.UUID]model.NoteAccessInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterNotes indicates an expected call of FilterNotes.
func (mr *MockPoliticsServiceMockRecorder) FilterNotes(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNotes", reflect.TypeOf((*MockPoliticsService)(nil).FilterNotes), ctx, req)
}

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// GetUserIDByTelegramID mocks base method.
func (m *MockuserService) GetUserIDByTelegramID(ctx context.Context, telegramID string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByTelegramID", ctx, telegramID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByTelegramID indicates an expected call of GetUserIDByTelegramID.
func (mr *MockuserServiceMockRecorder) GetUserIDByTelegramID(ctx, telegramID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByTelegramID", reflect.TypeOf((*MockuserService)(nil).GetUserIDByTelegramID), ctx, telegramID)
}
