// Code generated by MockGen. DO NOT EDIT.
// Source: resource.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "auth-service/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockresourceService is a mock of resourceService interface.
type MockresourceService struct {
	ctrl     *gomock.Controller
	recorder *MockresourceServiceMockRecorder
}

// MockresourceServiceMockRecorder is the mock recorder for MockresourceService.
type MockresourceServiceMockRecorder struct {
	mock *MockresourceService
}

// NewMockresourceService creates a new mock instance.
func NewMockresourceService(ctrl *gomock.Controller) *MockresourceService {
	mock := &MockresourceService{ctrl: ctrl}
	mock.recorder = &MockresourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresourceService) EXPECT() *MockresourceServiceMockRecorder {
	return m.recorder
}

// UpdateResource mocks base method.
func (m *MockresourceService) UpdateResource(ctx context.Context, req model.UpdateResourceRequest) (model.UpdateResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", ctx, req)
	ret0, _ := ret[0].(model.UpdateResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockresourceServiceMockRecorder) UpdateResource(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockresourceService)(nil).UpdateResource), ctx, req)
}
