name: integration-tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout auth-service
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout platform-testkit
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.TESTKIT_REPO }}
          path: platform-testkit
          ref: BZ-184 # временно, пока налаживается workflow
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          persist-credentials: false

      - name: Build auth image
        run: docker build -t auth-service:test-${GITHUB_SHA} .

      - name: Start integration environment
        working-directory: platform-testkit
        env:
          AUTH_IMAGE: auth-service:test-${{ github.sha }}
          AUTOTESTS_TAG: latest
        run: |
          set -euo pipefail
          make integration-up

      - name: Seed integration data
        working-directory: platform-testkit
        env:
          AUTH_IMAGE: auth-service:test-${{ github.sha }}
          AUTOTESTS_TAG: latest
        run: |
          set -euo pipefail
          make integration-seed

      - name: Run integration tests
        working-directory: platform-testkit
        env:
          AUTH_IMAGE: auth-service:test-${{ github.sha }}
          AUTOTESTS_TAG: latest
        run: |
          set -euo pipefail
          make integration-test

      - name: Cleanup
        if: always()
        working-directory: platform-testkit
        env:
          AUTH_IMAGE: auth-service:test-${{ github.sha }}
        run: |
          docker compose --env-file ./env/compose.env -f ./compose/docker-compose.intergation.yaml down -v --remove-orphans