// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// Mockhandler is a mock of handler interface.
type Mockhandler struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerMockRecorder
}

// MockhandlerMockRecorder is the mock recorder for Mockhandler.
type MockhandlerMockRecorder struct {
	mock *Mockhandler
}

// NewMockhandler creates a new mock instance.
func NewMockhandler(ctrl *gomock.Controller) *Mockhandler {
	mock := &Mockhandler{ctrl: ctrl}
	mock.recorder = &MockhandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandler) EXPECT() *MockhandlerMockRecorder {
	return m.recorder
}

// FilterNotes mocks base method.
func (m *Mockhandler) FilterNotes(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNotes", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterNotes indicates an expected call of FilterNotes.
func (mr *MockhandlerMockRecorder) FilterNotes(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNotes", reflect.TypeOf((*Mockhandler)(nil).FilterNotes), c)
}

// Health mocks base method.
func (m *Mockhandler) Health(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockhandlerMockRecorder) Health(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*Mockhandler)(nil).Health), c)
}

// Version mocks base method.
func (m *Mockhandler) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockhandlerMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*Mockhandler)(nil).Version))
}

// MockversionHandler is a mock of versionHandler interface.
type MockversionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockversionHandlerMockRecorder
}

// MockversionHandlerMockRecorder is the mock recorder for MockversionHandler.
type MockversionHandlerMockRecorder struct {
	mock *MockversionHandler
}

// NewMockversionHandler creates a new mock instance.
func NewMockversionHandler(ctrl *gomock.Controller) *MockversionHandler {
	mock := &MockversionHandler{ctrl: ctrl}
	mock.recorder = &MockversionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockversionHandler) EXPECT() *MockversionHandlerMockRecorder {
	return m.recorder
}

// Version mocks base method.
func (m *MockversionHandler) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockversionHandlerMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockversionHandler)(nil).Version))
}

// MockhealthHandler is a mock of healthHandler interface.
type MockhealthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockhealthHandlerMockRecorder
}

// MockhealthHandlerMockRecorder is the mock recorder for MockhealthHandler.
type MockhealthHandlerMockRecorder struct {
	mock *MockhealthHandler
}

// NewMockhealthHandler creates a new mock instance.
func NewMockhealthHandler(ctrl *gomock.Controller) *MockhealthHandler {
	mock := &MockhealthHandler{ctrl: ctrl}
	mock.recorder = &MockhealthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhealthHandler) EXPECT() *MockhealthHandlerMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockhealthHandler) Health(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockhealthHandlerMockRecorder) Health(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockhealthHandler)(nil).Health), c)
}

// MocknotesEditor is a mock of notesEditor interface.
type MocknotesEditor struct {
	ctrl     *gomock.Controller
	recorder *MocknotesEditorMockRecorder
}

// MocknotesEditorMockRecorder is the mock recorder for MocknotesEditor.
type MocknotesEditorMockRecorder struct {
	mock *MocknotesEditor
}

// NewMocknotesEditor creates a new mock instance.
func NewMocknotesEditor(ctrl *gomock.Controller) *MocknotesEditor {
	mock := &MocknotesEditor{ctrl: ctrl}
	mock.recorder = &MocknotesEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotesEditor) EXPECT() *MocknotesEditorMockRecorder {
	return m.recorder
}

// FilterNotes mocks base method.
func (m *MocknotesEditor) FilterNotes(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNotes", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilterNotes indicates an expected call of FilterNotes.
func (mr *MocknotesEditorMockRecorder) FilterNotes(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNotes", reflect.TypeOf((*MocknotesEditor)(nil).FilterNotes), c)
}

// MockmiddlewareHandler is a mock of middlewareHandler interface.
type MockmiddlewareHandler struct {
	ctrl     *gomock.Controller
	recorder *MockmiddlewareHandlerMockRecorder
}

// MockmiddlewareHandlerMockRecorder is the mock recorder for MockmiddlewareHandler.
type MockmiddlewareHandlerMockRecorder struct {
	mock *MockmiddlewareHandler
}

// NewMockmiddlewareHandler creates a new mock instance.
func NewMockmiddlewareHandler(ctrl *gomock.Controller) *MockmiddlewareHandler {
	mock := &MockmiddlewareHandler{ctrl: ctrl}
	mock.recorder = &MockmiddlewareHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmiddlewareHandler) EXPECT() *MockmiddlewareHandlerMockRecorder {
	return m.recorder
}

// CheckToken mocks base method.
func (m *MockmiddlewareHandler) CheckToken(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockmiddlewareHandlerMockRecorder) CheckToken(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockmiddlewareHandler)(nil).CheckToken), next)
}
